name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'perf'
      - 'performance'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'test'
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'pre'
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feat'
      - 'feature'
      - 'minor'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'patch'
      - 'chore'
  default: patch
template: |
  ## What's Changed
  $CHANGES

autolabeler:
  - label: 'feat'
    branch:
      - '/^feat\/.+/'
    title:
      - '/^feat(\(.+\))?:/i'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
    title:
      - '/^fix(\(.+\))?:/i'
  - label: 'docs'
    branch:
      - '/^docs?\/.+/'
    title:
      - '/^docs?(\(.+\))?:/i'
  - label: 'chore'
    branch:
      - '/^chore\/.+/'
      - '/^ci\/.+/'
      - '/^refactor\/.+/'
    title:
      - '/^(chore|ci|refactor)(\(.+\))?:/i'
  - label: 'perf'
    branch:
      - '/^perf\/.+/'
    title:
      - '/^perf(\(.+\))?:/i'
