---
name: Documentation Issue
description: Report issues with documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please report any issues you've found.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation has the issue?
      options:
        - README.md
        - API Documentation
        - Code Comments
        - Examples
        - Contributing Guide
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Location
      description: Where is the documentation located?
      placeholder: e.g., README.md line 42, or URL to docs.rs
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue.
      placeholder: |
        What's wrong with the documentation?
        - Is it unclear?
        - Is it incorrect?
        - Is it missing?
        - Is it outdated?
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How should the documentation be improved?
      placeholder: |
        Provide your suggested fix or improvement.
        If possible, include the corrected text.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
      placeholder: |
        - Screenshots
        - Links
        - Related issues

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting your documentation issue.
      options:
        - label: I have searched for similar documentation issues and couldn't find any.
          required: true
        - label: I have provided all the required information above.
          required: true