---
name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your input helps make RustAPI better for everyone.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief description of the feature you'd like to see.
      placeholder: What feature would you like to see added?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
      placeholder: |
        Is there a problem this feature would solve? If so, describe it.
        For example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: |
        Describe how you think this feature should work. Include:
        - API design
        - Usage examples
        - Implementation details
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions?
      placeholder: |
        Describe any alternative solutions or features you've considered.
        Why would this be better than the alternatives?

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        - Screenshots
        - Mockups
        - Related issues
        - Links to similar features in other projects

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting your feature request.
      options:
        - label: I have searched for similar feature requests and couldn't find any.
          required: true
        - label: This feature would benefit other users, not just me.
          required: true
        - label: I have provided all the required information above.
          required: true