name: Release Drafter

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # write releases
      pull-requests: read
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch'
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  publish_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag'
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          publish: true
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  update_pr_label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
